[package]
name = "qpkg"
version = "0.1.2"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.22"
aho-corasick = "1.1.3"
walkdir = "2.5.0"
which = "7.0.3"
