[general]
target = "x86_64-unknown-linux-gnu"
sysroot = "sysroot"
recipes_dir = "recipes"
host_recipes_dir = "host-recipes"
meta_dir = "meta"
build_root = "."
threads = 18
templates_file = "helpers.toml"

# config for the build machine (the machine that is running the build commands)
[build]
cc = "clang"
cxx = "clang++"
cflags = "-march=native -pipe"
cxxflags = "-march=native -pipe"
ldflags = "-fuse-ld=lld"

# config for the target machine (when building packages that are meant to run on `target`)
[target]
cc = "clang"
cxx = "clang++"
cflags = "-march=native -pipe"
cxxflags = "-march=native -pipe"
ldflags = "-fuse-ld=lld"
